# Generated by Django 5.0.7 on 2024-07-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bublik',
            name='text',
        ),
    ]
