# Generated by Django 5.0.7 on 2024-07-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_bublik_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bublik',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
